### ISSUE TITLE
Logo: Version w/ transparency? 

### ISSUE THREAD

**Issue by thomas-thackery** [woodwarddesign/ap-helicopters#1]
![logo](https://cloud.githubusercontent.com/assets/536441/4999407/f0c42a12-6996-11e4-8254-3dc25473263e.gif)

**Comment by mlwoodward** [comment]
Tried to pull logo out from background.  It did not render well.  Requested logo with transparency from Gary.

**Comment by mlwoodward** [comment]
![ap-helicopters-logo](https://cloud.githubusercontent.com/assets/4562222/5039663/ab39f618-6b56-11e4-83b7-77f1503f0543.png)

PNG version of logo attached.  Also emailed directly to @kveldalf
